spring.application.name=nexuscommerce
spring.datasource.url=jdbc:postgresql://localhost:5432/nexuscommerce
spring.datasource.username=aastha
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true